name: build

workflow_call:
    inputs:
        dep-env:
            required: true
            type: string
    secrets:
        env_dir:
            required: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
          run: echo building ${{github.event.inputs.dep-env}}
