name: build

on:
  workflow_call:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]
    
env:
  ARTIFACT_NAME: build-${{ github.repository }}-${{ github.run_id }}-${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: announce intentions
      run: echo building ${{ env.ARTIFACT_NAME }}
      
    - name: output artifact information
      run: echo "::notice title='Build Artifact'::${{ env.ARTIFACT_NAME }}"
