name: build and deploy

on:
  workflow_dispatch:
    inputs:
      dep-env:
        type: choice
        description: environment to deploy to
        required: true
        options:
          - qa-1
          - qa-2
          - stag
          - prod

  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]
    
env:
  ARTIFACT_NAME: deploy-artifact-v1

jobs:
  build:
    uses: iccowan/reusable-workflows-test/.github/workflows/build.yml@main
    with:
      artifact-name: ${{ env.ARTIFACT_NAME }}

  qa-1:
    uses: iccowan/reusable-workflows-test/.github/workflows/deploy.yml@main
    with:
      dep-env: 'qa-1'
      artifact-name: ${{ env.ARTIFACT_NAME }}
    secrets:
      env_dir: ${{ secrets.ENV_NAME }}

    needs: build
    if: ${{ github.event.inputs.dep-env == 'qa-1' }}

  qa-2:
    uses: iccowan/reusable-workflows-test/.github/workflows/deploy.yml@main
    with:
      dep-env: 'qa-2'
      artifact-name: ${{ env.ARTIFACT_NAME }}
    secrets:
      env_dir: ${{ secrets.ENV_NAME }}

    needs: build
    if: ${{ github.event.inputs.dep-env == 'qa-2' }}

  stag:
    uses: iccowan/reusable-workflows-test/.github/workflows/deploy.yml@main
    with:
      dep-env: 'stag'
      artifact-name: ${{ env.ARTIFACT_NAME }}
    secrets:
      env_dir: ${{ secrets.ENV_NAME }}

    needs: build
    if: ${{ github.event.inputs.dep-env == 'stag' || (github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch') }}

  prod:
    uses: iccowan/reusable-workflows-test/.github/workflows/deploy.yml@main
    with:
      dep-env: 'prod'
      artifact-name: ${{ env.ARTIFACT_NAME }}
    secrets:
      env_dir: ${{ secrets.ENV_NAME }}

    needs: build
    if: ${{ github.event.inputs.dep-env == 'prod' }}
