name: deploy to environment template

on:
  workflow_call:
    inputs:
      dep_env:
        required: true
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.dep_env }}

    steps:
    - name: retrieve artifact for deploy
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}

    - name: extract artifact
      run: |
        tar -zxvf ${{ inputs.artifact_name }}.tar.gz
        rm ${{ inputs.artifact_name }}.tar.gz
        
    - name: announce intentions
      run: echo Deploying ${{ inputs.artifact_name }} to ${{ inputs.dep_env }}
