name: deploy to environment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
    secrets:
      ENV_NAME:
       required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}

    steps:
    - uses: actions/checkout@v2

    - name: announce intentions
      run: echo deploying ${{inputs.artifact-name}} to ${{inputs.environment}} on ${{ secrets.ENV_NAME }}

