name: deploy to environment

workflow_call:
    inputs:
        dep-env:
            required: true
            type: string
    secrets:
        env_dir:
            required: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v2

        - name: announce intentions
          run: echo deploying to ${{github.event.inputs.dep-env}}

