name: deploy to environment

on:
  workflow_call:
    inputs:
      dep-env:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{inputs.dep-env}}

    steps:
    - uses: actions/checkout@v2

    - name: announce intentions
      run: echo deploying ${{inputs.artifact-name}} to ${{inputs.dep-env}} on ${{ secrets.ENV_NAME }}

